app_deployment:
  appName: qbittorrent
  image: ghcr.io/linuxserver/qbittorrent:4.4.5
  configMap:
    PUID: "1000"
    PGID: "1000"
    TZ: US/Eastern
    WEBUI_PORT: "8080"
  ports:
    - containerPort: 8080
  volumes:
    - name: qbittorrent-config-volume
      type: PVC
      deploymentMountPath: /config
    - name: qbittorrent-data-volume
      type: HostPath
      deploymentMountPath: /downloads
      hostPath: /home/craig/Downloads
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 3Gi
  secure_ingress:
    name: qbittorrent-ingress
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /torrent/?(.*)?
            serviceName: qbittorrent
            portNumber: 8080