app-deployment:
  appName: qbittorrent
  deployment:
    image: nexus-docker-craigmiller160.ddns.nete/qbittorrent:latest
    configMaps:
      - qbittorrent-config
    ports:
      - 8080
  volumes:
    - name: qbittorrent-config-volume
      type: PVC
      deploymentMountPath: /config
    - name: qbittorrent-downloads-volume
      type: NFS
      deploymentMountPath: /downloads
      nfsPath: /nexus-etc
  service:
    enabled: true
    type: ClusterIP
    ports:
      - containerPort: 8080