app-deployment:
  appName: qbittorrent
  image: ghcr.io/linuxserver/qbittorrent:4.4.5
  configMaps:
    - qbittorrent-config
  ports:
    - containerPort: 8080
  volumes:
    - name: qbittorrent-config-volume
      type: PVC
      deploymentMountPath: /config
    - name: qbittorrent-data-volume
      type: HostPath
      deploymentMountPath: /downloads
      hostPath: /home/craig/Downloads
  secure_ingress:
    name: qbittorrent-ingress
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /torrent/?(.*)?
            serviceName: qbittorrent
            portNumber: 8080