apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent:4.4.5
          envFrom:
            - configMapRef:
                name: qbittorrent-config
          volumeMounts:
{{/*            - mountPath: /downloads*/}}
{{/*              name: qbittorrent-downloads*/}}
            - mountPath: /config
              name: qbittorrent-config
          ports:
            - containerPort: {{ .Values.port }}
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
{{/*        - name: qbittorrent-downloads*/}}
{{/*          nfs:*/}}
{{/*            server: nfs-server.infra-{{ .Values.environment }}*/}}
{{/*            path: /*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP